name: "App release"
on:
  release:
    types:
      - released
jobs:
  trigger-app-release:
    uses: FLECS-Technologies/app-sdk/.github/workflows/trigger_app_release.yml@main
    with:
      app-repo: ${{ github.repository }}
      release-tag: ${{ github.event.release.tag_name }}
      app-version: ${{ github.event.release.tag_name }}
    secrets:
      APP_RELEASE_TOKEN: ${{ secrets.APP_RELEASE_TOKEN }}
